### ISSUE TITLE
Accuracy of single precision floating point math

### ISSUE THREAD

**Issue by bethmal** [TimPaterson/ArmMathM0#2]
Hi @TimPaterson 

We are evaluating ArmMathM0 on STM32G0B0 and observed the difference between ArmMathM0 and calculator regarding to floating point math functions.
fadd: 2205.1969 + 270.8886, ArmMathM0: 2476.08569, calculator: 2476.0855
fsub: 2205.1969 - 270.8886, ArmMathM0: 1934.30835, calculator: 1934.3083
fmul: 2205.1969 * 270.8886, ArmMathM0: 597362.75, calculator: 597362.70096534
fdiv: 2205.1969 / 270.8886, ArmMathM0: 8.14060402, calculator: 8.140604292687105

The outputs of ArmMathM0 are pretty close to the outputs of calculator, except for slight difference in decimal part.

Are the differences expected accuracy lose? Anyway to improve that?

Thanks.

**Comment by TimPaterson** [comment]
Single precision has only 24 bits of precision (about 7 digits). If you need more precision you must use double (53 bits, about 16 digits).  ArmMathM0 gives the closest possible answer within for a given precision.

**Comment by bethmal** [comment]
Thanks, @TimPaterson Just close the issue.
